<?php

/**
 * Implements hook_code_sign_info().
 */
function code_sign_gnupg_code_sign_info() {
  $signers = array();

  $signers['gnupg'] = array(
    'title' => t('GnuPG'),
    'sign callback' => 'code_sign_gnupg_sign',
    'verify callback' => 'code_sign_gnupg_verify',
    'status callback' => 'code_sign_gnupg_status',
    'public keychain callback' => 'code_sign_gnupg_get_verification_keys',
    'private keychain callback'  => 'code_sign_gnupg_get_private_keys',
    'file' => backdrop_get_path('module', 'code_sign_gnupg') . '/gnupg.codesign.inc',
  );

  return $signers;
}

/**
 * Implements hook_menu().
 */
function code_sign_gnupg_menu() {
  $items = array();

  $items['admin/config/system/code-sign/gnupg'] = array(
    'title' => 'GnuPG',
    'page callback' => 'backdrop_get_form',
    'page arguments' => array('code_sign_gnupg_admin_form'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_LOCAL_TASK,
    'file' => 'code_sign_gnupg.admin.inc',
  );
  $items['admin/config/system/code-sign/gnupg/settings'] = array(
    'title' => 'Settings',
    'weight' => -10,
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );
  $items['admin/config/system/code-sign/gnupg/import-key'] = array(
    'title' => 'Import Key',
    'page callback' => 'backdrop_get_form',
    'page arguments' => array('code_sign_gnupg_admin_import_key_form'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_LOCAL_TASK,
    'file' => 'code_sign_gnupg.admin.inc',
  );

  return $items;
}

